version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    ports:
      - "5000:5000"
    depends_on:
      - redis

  consumer:
    build: ./consumer
    depends_on:
      - redis
